version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-vpn-bot
    restart: always
    env_file:
      - .env
    working_dir: /app
    command: ["python", "main.py"]
    volumes:
      # Монтируем локальную папку с базой внутрь контейнера
      - ./database:/app/database


